### ISSUE TITLE
smsResponder - Log incoming SMS messages into database

### ISSUE THREAD

**Issue by dccabs** [dccabs/housecallmd#166]
*Create a smsMessages table in supabase.
*When someone sends an sms message to the twilio number, log that message into the database.
*The file that handles the SMS is located at `pages/api/smsResponder.js` 
*The payload params that twilio sends are demonstrated here.
https://www.twilio.com/docs/messaging/guides/webhook-request#request-parameters
*Our twilio phone number is `+12525125702`, sending a text to this will kick off the webhooks post to `pages/api/smsResponder.js` and include the payload of all the information.
*I think the payload information we want is, "from" which is the users number, and "body" which is their message.
*Data we want to capture,  number, sender first name, sender last name, message, timestamp.  
*My guess is we'd want to have a foreign key relationship to the person's entry in the userList.

I think we probably would use postman to create the POST request to localhost, since twilio won't be able to see localhost.  Or we could do some type of ngrok to expose your local host to twilio to test this.

**Comment by vbantilan** [comment]
1. Created table called sms_log (see photo below together with its foreign key relationship)
![image](https://user-images.githubusercontent.com/89785433/131680584-174244d5-a895-41cc-b5b7-941a7fac18be.png)

continue working in twilio's part

**Comment by vbantilan** [comment]
Update: 

Already capture the message if someone sent a number to the twilio's phone number- see record in database in the photo below
![image](https://user-images.githubusercontent.com/89785433/132234042-c4613420-df0e-468e-9e81-b6f964b1025e.png)

And see the body object that they webhook received
![image](https://user-images.githubusercontent.com/89785433/132234080-f91260b8-d1ba-4944-8c43-2fb4c0508461.png)

However, there isn't any data that we could get the sender's first name and sender's last name because it wasn't provded by the twilios body object that they send in the webhook.

**Comment by vbantilan** [comment]
- Next task: 
1. Check if the sms  belongs to a user and if it has made an appointment within the last 48 hours, if it did- save sms in the sms_log_message, if not send the auto responder

**Comment by dccabs** [comment]
done.
